// AUTO-GENERATED by scripts/gen-carousel.mjs — do not edit by hand.
// Regenerated before every build from the files in /public/videos.
export const CAROUSEL_VIDEOS: string[] = [
  "captions-carousel-video-1-optimized-av1.webm",
  "captions-carousel-video-2-optimized-av1.webm",
  "captions-carousel-video-3-optimized-av1.webm",
  "captions-carousel-video-6-optimized-av1.webm",
  "captions-carousel-video-7-optimized-av1.webm",
  "captions-carousel-video-8-optimized-av1.webm",
  "captions-carousel-video-9-optimized-av1.webm",
  "captions-carousel-video-10-optimized-av1.webm",
  "captions-carousel-video-11-optimized-av1.webm"
];
