// AUTO-GENERATED by scripts/gen-carousel.mjs — do not edit by hand.
// Regenerated before every build from the files in /public/videos.
export const CAROUSEL_VIDEOS: string[] = [
  "reel-1.mp4",
  "reel-2.mp4",
  "reel-3.mp4",
  "reel-4.mp4",
  "reel-5.mp4",
  "reel-6.mp4",
  "reel-7.mp4",
  "reel-8.mp4",
  "reel-9.mp4"
];
