// AUTO-GENERATED by scripts/gen-carousel.mjs — do not edit by hand.
// Regenerated before every build from the files in /public/videos.
export const CAROUSEL_VIDEOS: string[] = [
  "reel-1.webm",
  "reel-2.webm",
  "reel-3.webm",
  "reel-4.webm",
  "reel-5.webm",
  "reel-6.webm",
  "reel-7.webm",
  "reel-8.webm",
  "reel-9.webm"
];
